<a href="https://colab.research.google.com/github/kirtijha014/Drugs-Classification/blob/main/DrugsClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DRUG PREDICTION FOR CARDIOVASCULAR DISEASES

Created by Kirti Jha

Introduction- The model takes input parameters such as Age, Sex, BP ,Cholesterol and Na-to-K values and according to these values will predict the Drug out of five different drugs Captopril, Digoxin, Atropine, Theophilline, Isoprenaline.

Importing pandas and Numpy libraries.
*   Pandas - pandas pyhton library is used for handling data frames.
*   Numpy - numpy library is used for handling 1D , 2D arrays performing mathematical calculation.
The data is stored in GitHub repository. It is directly loaded as pandas dataframe from the link of the data provided.

In [9]:
import pandas as pd
import numpy as np
drug = pd.read_csv("https://raw.githubusercontent.com/RD1coder/Drug/main/drug200.csv")

After Importing the dataset, the dataset will be split into featurs and labels. X variables contains all the features and Y variable contains the target column of the corresponding drugs.

The main dataset is also printed to view the size and shape of data.

In [10]:
x,y=drug.shape
X = drug.iloc[:,:-1].values 
Y = drug.iloc[:,-1].values
Y.shape

(200,)

from google.colab import drive drive.mount('/content/drive')

Now the features contain categorical data like in sex M and F, in bp low, normal and high. The mathematical model will not be able to handle these categorical values. So for processing categories we need to encode them. The encoding is done using OneHot Encoder. This converts the model into corresponding dummy variables.

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# changing X categories
ct = ColumnTransformer(transformers=[("encode",OneHotEncoder(),[1])], remainder="passthrough")
X = np.array(ct.fit_transform(X) )
# changing X categories
ct = ColumnTransformer(transformers=[("encode",OneHotEncoder(),[3])], remainder="passthrough")
X = np.array(ct.fit_transform(X) )
# changing X categories
ct = ColumnTransformer(transformers=[("encode",OneHotEncoder(),[6])], remainder="passthrough")
X = np.array(ct.fit_transform(X) )

To encode target column we will be using a python script. The categorical data in target have 5 drugs. To encode them into 0,1,2,3 and 4 values this python block is used.

In [12]:
x,y=drug.shape

labels = []

for i in Y:
    if i in labels:
        pass
    else:
        labels.append(i)

print(labels)

for l in range(x):
    for i in range(len(labels)):
        if (labels[i]==Y[l]):
            Y[l] = i
        else :
            pass
Y = Y.astype(np.float)

['Captopril', 'Digoxin', 'Atropine', 'Theophilline', 'Isoprenaline']


Now the Features and Labels are split into test set and training set of data. The training set is used for model generation and test set is used for model parametes calculation. The test size is 20% of the original data.

In [13]:
#Test Train Split
from sklearn.model_selection import train_test_split
X_train, X_test , Y_train , Y_test = train_test_split(X,Y, test_size=.20,random_state=42)

In this block of code the model is imported from SKlearn library. The model used is Logistic Regression which is readily available in Sklearn library.

After the model is called the model is provided with training set data for model generation.

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

Now once the model is successfully we can calculate accuracy of the model. There is a inbult method for prediction and accuracy calculation named as .predict( ) and .score( ) repectively. The calculated is 97.5 %.

In [15]:
y_pred = classifier.predict(X_test)
accuracy = classifier.score(X_test,Y_test)
accuracy

0.975

These are the prediction results for testing feature data. It is given for comparison with actual data given in next cell.

In [16]:
y_pred

array([2., 0., 2., 1., 0., 0., 0., 2., 3., 2., 3., 2., 0., 3., 4., 0., 4.,
       2., 1., 0., 4., 2., 2., 0., 0., 0., 1., 2., 0., 2., 0., 1., 0., 0.,
       3., 0., 2., 3., 0., 3.])

This is the actual data:

In [17]:
Y_test

array([2., 0., 2., 1., 0., 0., 0., 2., 3., 2., 3., 2., 0., 3., 4., 0., 4.,
       2., 1., 0., 4., 2., 2., 0., 0., 0., 1., 2., 0., 2., 0., 1., 1., 0.,
       3., 0., 2., 3., 0., 3.])

This block of code is for creating confusion matrix which requires the prediction data and actual data. The confusion matric matrix is printed in form of a 2D array

In [18]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
cm

array([[15,  0,  0,  0,  0],
       [ 1,  4,  0,  0,  0],
       [ 0,  0, 11,  0,  0],
       [ 0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  3]])

This block of code is to calculate the F1 score of the model. The F1 score of the model is .971.

In [19]:
from sklearn.metrics import f1_score 
#for calculating  accuracy_score
print("f1_score =",f1_score(Y_test,y_pred, average='macro'))

f1_score = 0.9713261648745519


This is the deployment script. It asks for user input and generate the prediction of testing data provided.

In [ ]:
#the final test script
iparry =[]
sex = input("Enter gender 'F' for femnale 'M for male' -- ").upper()
BP = input("Enter BP 'LOW','NORMAL','HIGH' -- ").upper()
Cholesterol = input("Enter Cholesterol 'NORMAL' or 'HIGH' -- ").upper()
Age = int(input("Enter Age -- "))
Na_to_K = float(input("Enter Na_to_K value 'some value between 0 to 40' -- "))

if (sex == "F"):
  iparry.extend([0.0,1.0])
else:
  iparry.extend([1.0,0.0])

if ( BP == "LOW"):
  iparry.extend([0.0,0.0,1.0])
elif( BP == "NORMAL"):
  iparry.extend([0.0,1.0,0.0])
else:
  iparry.extend([1.0,0.0,0.0])

if (Cholesterol == "NORMAL"):
  iparry.extend([0.0,1.0])
else:
  iparry.extend([1.0,0.0])  

iparry.append(Age)
iparry.append(Na_to_K)
temp = []
temp.append(iparry)
print(iparry)
ans = classifier.predict(temp)
print("The drug you should take is -- "+labels[int(ans)])